# Generated by Django 4.2 on 2023-04-28 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manzara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joy_nomi', models.CharField(max_length=30)),
                ('rasm', models.FileField(upload_to='')),
                ('matn', models.CharField(max_length=1000)),
                ('sana', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shaxar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('rasm', models.FileField(upload_to='')),
                ('matn', models.CharField(max_length=1000)),
                ('sana', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Din',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('din_malumot', models.CharField(max_length=1000)),
                ('rasm', models.FileField(upload_to='')),
                ('shaxar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Blog.shaxar')),
            ],
        ),
    ]
